"""
Module: api/routes/admin.py
Description: API endpoints for admin role.
             Provides analytics dashboard with application statistics,
             model performance metrics, fairness report and
             officer activity tracking.
             Admin role is analytics-only — no application decisions.

Endpoints:
    GET /admin/stats                - Full dashboard statistics
    GET /admin/applications         - All applications with filters
    GET /admin/model/metrics        - Model comparison metrics
    GET /admin/model/fairness       - Fairness report by demographic
    GET /admin/model/confusion      - Confusion matrix image
    GET /admin/model/shap           - SHAP feature importance image
    GET /admin/officers/activity    - Officer performance summary
    GET /admin/users                - All registered users
"""

import os
import json
import csv
from datetime import datetime, date
from typing import Optional
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from sqlalchemy import func

from api.models.database import get_db
from api.models.entities import (
    Application, Decision, Prediction, User
)
from api.routes.auth import require_admin
from api.config import AppStatus, SCHEME_LABELS

router = APIRouter(prefix="/admin", tags=["Admin"])

# ─── ML Output Files Path ─────────────────────────────────────
# These files are generated by NSAP_train.ipynb and stored in ml/
ML_DIR = Path(__file__).resolve().parents[3] / "ml"

MODEL_COMPARISON_CSV = ML_DIR / "model_comparison.csv"
FAIRNESS_REPORT_CSV  = ML_DIR / "fairness_report.csv"
CONFUSION_MATRIX_PNG = ML_DIR / "output" / "confusion_matrix_catboost.png"
SHAP_SUMMARY_PNG     = ML_DIR / "output" / "shap_summary_plot.png"


# ─── Dashboard Statistics ─────────────────────────────────────
@router.get("/stats")
def get_dashboard_stats(
    current_user: User    = Depends(require_admin),
    db:           Session = Depends(get_db),
):
    """
    GET /api/v1/admin/stats

    Full admin dashboard statistics.
    Combines application counts, model performance
    and officer activity into a single response.

    Returns:
        dict: Complete dashboard statistics.
    """
    # ── Application Counts ────────────────────────────────────
    total = db.query(Application).count()

    by_status = {
        AppStatus.PENDING:       db.query(Application).filter(
            Application.status == AppStatus.PENDING).count(),
        AppStatus.AUTO_APPROVED: db.query(Application).filter(
            Application.status == AppStatus.AUTO_APPROVED).count(),
        AppStatus.NEEDS_REVIEW:  db.query(Application).filter(
            Application.status == AppStatus.NEEDS_REVIEW).count(),
        AppStatus.APPROVED:      db.query(Application).filter(
            Application.status == AppStatus.APPROVED).count(),
        AppStatus.REJECTED:      db.query(Application).filter(
            Application.status == AppStatus.REJECTED).count(),
    }

    # ── Scheme Distribution ───────────────────────────────────
    by_scheme = {}
    for scheme in ["OAP", "WP", "DP", "NOT_ELIGIBLE"]:
        by_scheme[scheme] = db.query(Prediction).filter(
            Prediction.predicted_scheme == scheme
        ).count()

    # ── Model Performance ─────────────────────────────────────
    # Average confidence across all predictions
    avg_conf_result = db.query(
        func.avg(Prediction.confidence_score)
    ).scalar()
    avg_confidence = round(float(avg_conf_result or 0), 4)

    # Needs review count and percentage
    needs_review_count = db.query(Prediction).filter(
        Prediction.needs_review == True
    ).count()
    needs_review_pct = round(
        (needs_review_count / total * 100) if total > 0 else 0, 1
    )

    # ── Officer Activity ──────────────────────────────────────
    total_officers  = db.query(User).filter(
        User.role == "officer"
    ).count()

    today           = datetime.now().date()
    decisions_today = db.query(Decision).filter(
        func.date(Decision.decided_at) == today
    ).count()

    total_decisions = db.query(Decision).count()

    # ── User Counts ───────────────────────────────────────────
    total_citizens = db.query(User).filter(
        User.role == "citizen"
    ).count()

    # ── State Distribution ────────────────────────────────────
    state_counts_raw = db.query(
        Application.state,
        func.count(Application.id).label("count")
    ).group_by(Application.state).all()

    by_state = {row[0]: row[1] for row in state_counts_raw}

    # ── Gender Distribution ───────────────────────────────────
    gender_counts_raw = db.query(
        Application.gender,
        func.count(Application.id).label("count")
    ).group_by(Application.gender).all()

    by_gender = {row[0]: row[1] for row in gender_counts_raw}

    # ── Recent Activity (last 7 days) ─────────────────────────
    from datetime import timedelta
    week_ago = datetime.now() - timedelta(days=7)

    recent_submissions = db.query(Application).filter(
        Application.submitted_at >= week_ago
    ).count()

    recent_decisions = db.query(Decision).filter(
        Decision.decided_at >= week_ago
    ).count()

    return {
        "generated_at":       datetime.now().isoformat(),
        "applications": {
            "total":           total,
            "by_status":       by_status,
            "by_scheme":       by_scheme,
            "by_state":        by_state,
            "by_gender":       by_gender,
        },
        "model": {
            "avg_confidence":      avg_confidence,
            "needs_review_count":  needs_review_count,
            "needs_review_pct":    needs_review_pct,
            "total_predictions":   db.query(Prediction).count(),
        },
        "officers": {
            "total_officers":   total_officers,
            "decisions_today":  decisions_today,
            "total_decisions":  total_decisions,
        },
        "users": {
            "total_citizens":   total_citizens,
            "total_officers":   total_officers,
            "total_users":      total_citizens + total_officers + 1,
        },
        "recent_activity": {
            "submissions_last_7_days": recent_submissions,
            "decisions_last_7_days":   recent_decisions,
        },
    }


# ─── All Applications ─────────────────────────────────────────
@router.get("/applications")
def get_all_applications(
    status_filter: Optional[str] = None,
    scheme_filter: Optional[str] = None,
    state_filter:  Optional[str] = None,
    gender_filter: Optional[str] = None,
    limit:         int           = 50,
    offset:        int           = 0,
    current_user:  User          = Depends(require_admin),
    db:            Session       = Depends(get_db),
):
    """
    GET /api/v1/admin/applications

    List all applications with rich filtering options.
    Admin can filter by status, scheme, state and gender.

    Args:
        status_filter (str): Filter by application status.
        scheme_filter (str): Filter by predicted scheme.
        state_filter  (str): Filter by applicant state.
        gender_filter (str): Filter by applicant gender.
        limit         (int): Max results (default 50).
        offset        (int): Pagination offset.

    Returns:
        dict: Paginated application list with summary stats.
    """
    query = db.query(Application)

    if status_filter:
        query = query.filter(Application.status == status_filter)
    if state_filter:
        query = query.filter(Application.state == state_filter)
    if gender_filter:
        query = query.filter(Application.gender == gender_filter)

    total = query.count()
    apps  = (
        query
        .order_by(Application.submitted_at.desc())
        .offset(offset)
        .limit(limit)
        .all()
    )

    results = []
    for app in apps:
        if scheme_filter and app.prediction:
            if app.prediction.predicted_scheme != scheme_filter:
                continue

        results.append({
            "id":               app.id,
            "status":           app.status,
            "submitted_at":     app.submitted_at.isoformat(),
            "age":              app.age,
            "gender":           app.gender,
            "state":            app.state,
            "social_category":  app.social_category,
            "predicted_scheme": app.prediction.predicted_scheme
                                if app.prediction else None,
            "confidence_score": app.prediction.confidence_score
                                if app.prediction else None,
            "needs_review":     app.prediction.needs_review
                                if app.prediction else None,
            "has_decision":     app.decision is not None,
            "citizen_name":     app.citizen.name
                                if app.citizen else None,
        })

    return {
        "total":  total,
        "limit":  limit,
        "offset": offset,
        "data":   results,
    }


# ─── Model Metrics ────────────────────────────────────────────
@router.get("/model/metrics")
def get_model_metrics(
    current_user: User = Depends(require_admin),
):
    """
    GET /api/v1/admin/model/metrics

    Load and return model comparison metrics from
    ml/model_comparison.csv generated by training notebook.

    Returns:
        dict: All model metrics for comparison table.

    Raises:
        HTTPException 404: If model_comparison.csv not found.
    """
    if not MODEL_COMPARISON_CSV.exists():
        raise HTTPException(
            status_code = status.HTTP_404_NOT_FOUND,
            detail      = (
                "model_comparison.csv not found. "
                "Run NSAP_train.ipynb to generate metrics."
            ),
        )

    metrics = []
    with open(MODEL_COMPARISON_CSV, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            metrics.append({
                "model_name":      row.get("Model", ""),
                "accuracy":        float(row.get("Accuracy", 0)),
                "precision":       float(row.get("Precision", 0)),
                "recall":          float(row.get("Recall", 0)),
                "f1_weighted":     float(row.get("F1_Weighted", 0)),
                "f1_dp":           float(row.get("F1_DP", 0)),
                "f1_not_eligible": float(row.get("F1_NOT_ELIGIBLE", 0)),
                "f1_oap":          float(row.get("F1_OAP", 0)),
                "f1_wp":           float(row.get("F1_WP", 0)),
            })

    # Best model is first row (sorted by F1 in notebook)
    best_model = metrics[0] if metrics else {}

    return {
        "best_model":  best_model,
        "all_models":  metrics,
        "source_file": "ml/model_comparison.csv",
    }


# ─── Fairness Report ──────────────────────────────────────────
@router.get("/model/fairness")
def get_fairness_report(
    current_user: User = Depends(require_admin),
):
    """
    GET /api/v1/admin/model/fairness

    Load and return fairness report from
    ml/fairness_report.csv generated by training notebook.

    Columns:
        Group_Column, Group, Count,
        Not_Eligible_Rate, Error_Rate,
        False_Not_Eligible_Rate, False_Eligible_Rate, Flag

    Returns:
        dict: Fairness metrics by demographic group.

    Raises:
        HTTPException 404: If fairness_report.csv not found.
    """
    if not FAIRNESS_REPORT_CSV.exists():
        raise HTTPException(
            status_code = status.HTTP_404_NOT_FOUND,
            detail      = (
                "fairness_report.csv not found. "
                "Run NSAP_train.ipynb to generate report."
            ),
        )

    entries    = []
    flagged    = []

    with open(FAIRNESS_REPORT_CSV, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            entry = {
                "group_column":            row.get("Group_Column", ""),
                "group":                   row.get("Group", ""),
                "count":                   int(row.get("Count", 0)),
                "not_eligible_rate":       float(row.get("Not_Eligible_Rate", 0)),
                "error_rate":              float(row.get("Error_Rate", 0)),
                "false_not_eligible_rate": float(row.get("False_Not_Eligible_Rate", 0)),
                "false_eligible_rate":     float(row.get("False_Eligible_Rate", 0)),
                "flag":                    row.get("Flag", "✓ OK"),
            }
            entries.append(entry)
            if entry["flag"] != "✓ OK":
                flagged.append(entry)

    return {
        "total_groups":  len(entries),
        "flagged_count": len(flagged),
        "flagged":       flagged,
        "all_groups":    entries,
        "source_file":   "ml/fairness_report.csv",
        "note": (
            "False_Not_Eligible_Rate: eligible person wrongly denied. "
            "False_Eligible_Rate: ineligible person wrongly approved. "
            "Flag threshold: > 5% triggers warning."
        ),
    }


# ─── Confusion Matrix Image ───────────────────────────────────
@router.get("/model/confusion")
def get_confusion_matrix(
    current_user: User = Depends(require_admin),
):
    """
    GET /api/v1/admin/model/confusion

    Serve confusion matrix PNG image generated by training notebook.

    Returns:
        FileResponse: PNG image file.

    Raises:
        HTTPException 404: If confusion matrix image not found.
    """
    if not CONFUSION_MATRIX_PNG.exists():
        raise HTTPException(
            status_code = status.HTTP_404_NOT_FOUND,
            detail      = (
                "Confusion matrix image not found. "
                "Run NSAP_train.ipynb to generate it."
            ),
        )

    return FileResponse(
        path         = str(CONFUSION_MATRIX_PNG),
        media_type   = "image/png",
        filename     = "confusion_matrix_catboost.png",
    )


# ─── SHAP Summary Image ───────────────────────────────────────
@router.get("/model/shap")
def get_shap_summary(
    current_user: User = Depends(require_admin),
):
    """
    GET /api/v1/admin/model/shap

    Serve SHAP feature importance summary PNG image
    generated by training notebook.

    Returns:
        FileResponse: PNG image file.

    Raises:
        HTTPException 404: If SHAP image not found.
    """
    if not SHAP_SUMMARY_PNG.exists():
        raise HTTPException(
            status_code = status.HTTP_404_NOT_FOUND,
            detail      = (
                "SHAP summary image not found. "
                "Run NSAP_train.ipynb to generate it."
            ),
        )

    return FileResponse(
        path       = str(SHAP_SUMMARY_PNG),
        media_type = "image/png",
        filename   = "shap_summary.png",
    )


# ─── Officer Activity ─────────────────────────────────────────
@router.get("/officers/activity")
def get_officer_activity(
    current_user: User    = Depends(require_admin),
    db:           Session = Depends(get_db),
):
    """
    GET /api/v1/admin/officers/activity

    Summary of all officers' decision activity.
    Shows total decisions, approvals, rejections and overrides
    for each officer — useful for monitoring officer performance.

    Returns:
        dict: List of officer activity summaries.
    """
    officers = db.query(User).filter(User.role == "officer").all()

    activity = []
    for officer in officers:
        decisions = db.query(Decision).filter(
            Decision.officer_id == officer.id
        ).all()

        total     = len(decisions)
        approved  = sum(1 for d in decisions if d.decision == "approved")
        rejected  = sum(1 for d in decisions if d.decision == "rejected")
        overrides = sum(1 for d in decisions if d.override_scheme)

        # Today's count
        today           = datetime.now().date()
        decided_today   = sum(
            1 for d in decisions
            if d.decided_at and d.decided_at.date() == today
        )

        activity.append({
            "officer_id":       officer.id,
            "officer_name":     officer.name,
            "officer_email":    officer.email,
            "total_decisions":  total,
            "approved":         approved,
            "rejected":         rejected,
            "overrides":        overrides,
            "decisions_today":  decided_today,
            "approval_rate":    round(
                (approved / total * 100) if total > 0 else 0, 1
            ),
        })

    # Sort by total decisions descending
    activity.sort(key=lambda x: x["total_decisions"], reverse=True)

    return {
        "total_officers": len(officers),
        "officers":       activity,
    }


# ─── All Users ────────────────────────────────────────────────
@router.get("/users")
def get_all_users(
    role_filter: Optional[str] = None,
    limit:       int           = 50,
    offset:      int           = 0,
    current_user: User         = Depends(require_admin),
    db:          Session       = Depends(get_db),
):
    """
    GET /api/v1/admin/users

    List all registered users with optional role filter.

    Args:
        role_filter (str): Filter by role (citizen/officer/admin).
        limit       (int): Max results (default 50).
        offset      (int): Pagination offset.

    Returns:
        dict: Paginated user list.
    """
    query = db.query(User)

    if role_filter:
        query = query.filter(User.role == role_filter)

    total = query.count()
    users = (
        query
        .order_by(User.created_at.desc())
        .offset(offset)
        .limit(limit)
        .all()
    )

    return {
        "total":  total,
        "limit":  limit,
        "offset": offset,
        "data": [
            {
                "id":         u.id,
                "name":       u.name,
                "email":      u.email,
                "phone":      u.phone,
                "role":       u.role,
                "state":      u.state,
                "is_active":  u.is_active,
                "created_at": u.created_at.isoformat(),
            }
            for u in users
        ],
    }